#Version = "1.0"

# 默认不分组的mapping直接会被放到default_mapping中

[[GroupRules]]
Name = "dev"
State = 1
RemoteHost = "192.168.56.112"

[[GroupRules.Rules]]
Name = "traffic"
State = 1
LocalPort = 8122
RemotePort = 8122



[[GroupRules.Rules]]
Name = "leio"
State = 0
LocalPort = 8020
RemotePort = 8111

[[GroupRules]]
Name = "test"
RemoteHost = "110.42.172.167"
