ActiveGroups = ["dev"]


[[MappingRules]]
Name = "app"
LocalPort = 19007
RemoteHost = "192.168.10.146"
RemotePort = 19007

#
#[[MappingRules]]
#Name = "jetbrain2"
#LocalPort = 8083
#RemoteHost = "110.42.172.167"
