[[MappingRules]]
Name = "app"
State = 0
LocalPort = 19007
RemoteHost = "192.168.10.130"
RemotePort = 19007


[[MappingRules]]
Name = "lest"
State = 1
LocalPort = 43523
RemoteHost = "192.168.10.130"
RemotePort = 7658

#
#[[MappingRules]]
#Name = "jetbrain2"
#LocalPort = 8083
#RemoteHost = "110.42.172.167"
